#############################################################################
# Generated by PAGE version 5.2
#  in conjunction with Tcl version 8.6
#  May 07, 2020 08:54:29 PM MDT  platform: Linux
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top43 {base} {
    global vTcl
    if {$base == ""} {
        set base .top43
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m59" -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 750x500
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 1
    wm maxsize $top 3825 1050
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Chess Gangsta"
    vTcl:DefineAlias "$top" "top" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    canvas $top.can51 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 75 -insertbackground black -relief ridge \
        -selectbackground #c4c4c4 -selectforeground black -takefocus 0 \
        -width 125 
    vTcl:DefineAlias "$top.can51" "board" vTcl:WidgetProc "top" 1
    button $top.but54 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -takefocus 0 
    vTcl:DefineAlias "$top.but54" "settings" vTcl:WidgetProc "top" 1
    button $top.but55 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -takefocus 0 
    vTcl:DefineAlias "$top.but55" "analyze" vTcl:WidgetProc "top" 1
    button $top.but56 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -takefocus 0 
    vTcl:DefineAlias "$top.but56" "play" vTcl:WidgetProc "top" 1
    ttk::separator $top.tSe58 \
        -orient vertical -takefocus 0 
    vTcl:DefineAlias "$top.tSe58" "TSeparator1" vTcl:WidgetProc "top" 1
    set site_3_0 $top.m59
    menu $site_3_0 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkDefaultFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    ttk::separator $top.tSe60 \
        -orient vertical -takefocus 0 
    vTcl:DefineAlias "$top.tSe60" "TSeparator2" vTcl:WidgetProc "top" 1
    ttk::separator $top.tSe61 \
        -takefocus 0 
    vTcl:DefineAlias "$top.tSe61" "TSeparator3" vTcl:WidgetProc "top" 1
    ttk::separator $top.tSe62 \
        -takefocus 0 
    vTcl:DefineAlias "$top.tSe62" "TSeparator4" vTcl:WidgetProc "top" 1
    vTcl:copy_lock $top.tSe62
    button $top.but64 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -takefocus 0 
    vTcl:DefineAlias "$top.but64" "backward" vTcl:WidgetProc "top" 1
    button $top.but65 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -takefocus 0 
    vTcl:DefineAlias "$top.but65" "forward" vTcl:WidgetProc "top" 1
    frame $top.fra68 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 45 -width 216 
    vTcl:DefineAlias "$top.fra68" "player_frame" vTcl:WidgetProc "top" 1
    set site_3_0 $top.fra68
    label $site_3_0.lab70 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) \
        -font {-family {Noto Sans Display} -size 18} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text Player 
    vTcl:DefineAlias "$site_3_0.lab70" "player_label" vTcl:WidgetProc "top" 1
    label $site_3_0.lab73 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -font {-family {Noto Sans Display} -size 18} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text 5:00 
    vTcl:DefineAlias "$site_3_0.lab73" "player_time" vTcl:WidgetProc "top" 1
    place $site_3_0.lab70 \
        -in $site_3_0 -x 0 -relx 0.065 -y 0 -rely 0.222 -width 0 \
        -relwidth 0.602 -height 0 -relheight 0.556 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab73 \
        -in $site_3_0 -x 0 -relx 0.741 -y 0 -rely 0.222 -width 0 \
        -relwidth 0.231 -height 0 -relheight 0.556 -anchor nw \
        -bordermode ignore 
    frame $top.fra74 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 45 -highlightcolor black -width 216 
    vTcl:DefineAlias "$top.fra74" "ai_frame" vTcl:WidgetProc "top" 1
    set site_3_0 $top.fra74
    label $site_3_0.lab70 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) \
        -font {-family {Noto Sans Display} -size 15} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text {Chess Gangsta} 
    vTcl:DefineAlias "$site_3_0.lab70" "ai_label" vTcl:WidgetProc "top" 1
    label $site_3_0.lab73 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -font {-family {Noto Sans Display} -size 18} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text 5:00 
    vTcl:DefineAlias "$site_3_0.lab73" "ai_time" vTcl:WidgetProc "top" 1
    place $site_3_0.lab70 \
        -in $site_3_0 -x 0 -relx 0.046 -y 0 -rely 0.111 -width 0 \
        -relwidth 0.648 -height 0 -relheight 0.778 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab73 \
        -in $site_3_0 -x 0 -relx 0.741 -y 0 -rely 0.222 -width 0 \
        -relwidth 0.231 -height 0 -relheight 0.556 -anchor nw \
        -bordermode ignore 
    label $top.lab78 \
        -anchor sw -background $vTcl(actual_gui_bg) \
        -font {-family {Noto Sans Display} -size 15} \
        -foreground $vTcl(actual_gui_fg) -text {Move History} 
    vTcl:DefineAlias "$top.lab78" "move_history_label" vTcl:WidgetProc "top" 1
    listbox $top.lis79 \
        -background white -font {-family {Noto Sans Display} -size 11} \
        -foreground $vTcl(actual_gui_fg) -height 300 -takefocus 0 -width 214 
    $top.lis79 configure -font "-family {Noto Sans Display} -size 11"
    $top.lis79 insert end text
    vTcl:DefineAlias "$top.lis79" "move_history" vTcl:WidgetProc "top" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.can51 \
        -in $top -x 0 -y 0 -width 0 -relwidth 0.667 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 
    place $top.but54 \
        -in $top -x 0 -relx 0.933 -y 0 -rely 0.12 -width 35 -relwidth 0 \
        -height 35 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but55 \
        -in $top -x 0 -relx 0.707 -y 0 -rely 0.8 -width 45 -relwidth 0 \
        -height 35 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but56 \
        -in $top -x 0 -relx 0.773 -y 0 -rely 0.8 -width 45 -relwidth 0 \
        -height 35 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tSe58 \
        -in $top -x 0 -relx 0.68 -y 0 -rely 0.006 -width 0 -relwidth 0.003 \
        -height 0 -relheight 0.99 -anchor nw -bordermode inside 
    place $top.tSe60 \
        -in $top -x 0 -relx 0.987 -y 0 -rely 0.004 -width 0 -relwidth 0.004 \
        -height 0 -relheight 0.992 -anchor nw -bordermode inside 
    place $top.tSe61 \
        -in $top -x 0 -relx 0.68 -y 0 -rely 0.004 -width 0 -relwidth 0.307 \
        -height 0 -relheight 0.004 -anchor nw -bordermode inside 
    place $top.tSe62 \
        -in $top -x 0 -relx 0.68 -y 0 -rely 0.996 -width 0 -relwidth 0.307 \
        -height 0 -relheight 0.004 -anchor nw -bordermode inside 
    place $top.but64 \
        -in $top -x 0 -relx 0.84 -y 0 -rely 0.8 -width 45 -relwidth 0 \
        -height 35 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but65 \
        -in $top -x 0 -relx 0.907 -y 0 -rely 0.8 -width 45 -relwidth 0 \
        -height 35 -relheight 0 -anchor nw -bordermode ignore 
    place $top.fra68 \
        -in $top -x 0 -relx 0.693 -y 0 -rely 0.89 -width 0 -relwidth 0.288 \
        -height 0 -relheight 0.09 -anchor nw -bordermode ignore 
    place $top.fra74 \
        -in $top -x 0 -relx 0.693 -y 0 -rely 0.02 -width 0 -relwidth 0.288 \
        -height 0 -relheight 0.09 -anchor nw -bordermode ignore 
    place $top.lab78 \
        -in $top -x 0 -relx 0.693 -y 0 -rely 0.136 -width 0 -relwidth 0.233 \
        -height 0 -relheight 0.054 -anchor nw -bordermode ignore 
    place $top.lis79 \
        -in $top -x 0 -relx 0.693 -y 0 -rely 0.196 -width 0 -relwidth 0.285 \
        -height 0 -relheight 0.6 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top43 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

